[workspace]
name = "raylib_mojo"
version = "0.1.0"
description = "Mojo bindings for raylib"
authors = ["Will Guimont <willguimont@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["linux-64"]

[dependencies]
max = ">=26.5.0"
mojo = ">=1.0.0"
cmake = "*"
ninja = "*"
make = "*"

[tasks]
format = "mojo format ."
format-check = "mojo format --check ."
build-raylib = "cmake -B build/raylib -S third_party/raylib -DBUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=ON && cmake --build build/raylib"
generate-bindings = "mojo run scripts/generate_bindings.mojo"
example-logo = "mojo run -I src -Xlinker -Lbuild/raylib/raylib -Xlinker -rpath -Xlinker build/raylib/raylib -Xlinker -lraylib examples/raylib_mojo_logo.mojo"
example-window = "mojo run -I src -Xlinker -Lbuild/raylib/raylib -Xlinker -rpath -Xlinker build/raylib/raylib -Xlinker -lraylib examples/basic_window.mojo"
example-bouncing-ball = "mojo run -I src -Xlinker -Lbuild/raylib/raylib -Xlinker -rpath -Xlinker build/raylib/raylib -Xlinker -lraylib examples/bouncing_ball.mojo"
example-collision = "mojo run -I src -Xlinker -Lbuild/raylib/raylib -Xlinker -rpath -Xlinker build/raylib/raylib -Xlinker -lraylib examples/shapes_collision_2d.mojo"
example-camera-2d = "mojo run -I src -Xlinker -Lbuild/raylib/raylib -Xlinker -rpath -Xlinker build/raylib/raylib -Xlinker -lraylib examples/core_2d_camera.mojo"
example-3d = "mojo run -I src -Xlinker -Lbuild/raylib/raylib -Xlinker -rpath -Xlinker build/raylib/raylib -Xlinker -lraylib examples/core_3d.mojo"
example-audio-stream = "mojo run -I src -Xlinker -Lbuild/raylib/raylib -Xlinker -rpath -Xlinker build/raylib/raylib -Xlinker -lraylib examples/audio_raw_stream.mojo"
example-sprite-anim = "mojo run -I src -Xlinker -Lbuild/raylib/raylib -Xlinker -rpath -Xlinker build/raylib/raylib -Xlinker -lraylib examples/textures_sprite_animation.mojo"
example-particle-assembly = "mojo run -I src -Xlinker -Lbuild/raylib/raylib -Xlinker -rpath -Xlinker build/raylib/raylib -Xlinker -lraylib examples/particle_assembly.mojo"
example-game-of-life = "mojo run -I src -Xlinker -Lbuild/raylib/raylib -Xlinker -rpath -Xlinker build/raylib/raylib -Xlinker -lraylib examples/shaders_game_of_life.mojo"
